export default {
  nodes: [
    // 检测状态
    {
      type: 'node',
      size: '70*48',
      shape: 'flow-rect',
      color: '#1890FF',
      // color: '#FA8C16',
      label: '检测状态',
      x: 150,
      y: 61,
      id: '1',
      index: 0,
      data: [
        {
          name: 'prop1',
          value: 'prop1',
        },
        {
          name: 'prop2',
          value: 'prop2',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '状态设置',
      x: 70,
      y: 201.5,
      id: '11',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '状态转移',
      x: 230,
      y: 201.5,
      id: '12',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    {
      type: 'node',
      size: '300*50',
      shape: 'flow-rhombus',
      // color: '#1890FF',
      color: 'rgb(19, 194, 194)',
      // color: '#FA8C16',
      label: 'State 在[1-47]区间 且 无需电池电压低 检测确认',
      x: 230,
      y: 320,
      id: '1211',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    // 确认状态
    {
      type: 'node',
      size: '70*48',
      shape: 'flow-rect',
      color: '#1890FF',
      // color: '#FA8C16',
      label: '确认状态',
      x: 400,
      y: 61,
      id: '2',
      index: 0,
      data: [
        {
          name: 'prop1',
          value: 'prop1',
        },
        {
          name: 'prop2',
          value: 'prop2',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '状态设置',
      x: 320,
      y: 201.5,
      id: '21',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '状态转移',
      x: 480,
      y: 201.5,
      id: '22',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    // 故障状态
    {
      type: 'node',
      size: '70*48',
      shape: 'flow-rect',
      color: '#1890FF',
      // color: '#FA8C16',
      label: '故障状态',
      x: 650,
      y: 61,
      id: '3',
      index: 0,
      data: [
        {
          name: 'prop1',
          value: 'prop1',
        },
        {
          name: 'prop2',
          value: 'prop2',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '状态设置',
      x: 570,
      y: 201.5,
      id: '31',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '状态转移',
      x: 650,
      y: 201.5,
      id: '32',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    {
      type: 'node',
      size: '50*50',
      shape: 'flow-circle',
      // color: '#1890FF',
      color: '#FA8C16',
      label: '故障处理',
      x: 730,
      y: 201.5,
      id: '33',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
    {
      type: 'node',
      size: '80*80',
      shape: 'flow-rhombus',
      color: 'rgb(19, 194, 194)',
      label: '故障处理',
      x: 570,
      y: 320,
      id: '3111',
      index: 1,
      data: [
        {
          name: 'prop3',
          value: 'prop3',
        },
        {
          name: 'prop4',
          value: 'prop4',
        },
      ],
    },
  ],
  edges: [
    // 检测状态下的连接边
    {
      source: '1',
      sourceAnchor: 2,
      target: '11',
      targetAnchor: 0,
      id: '111',
      index: 4,
    },
    {
      source: '1',
      sourceAnchor: 2,
      target: '12',
      targetAnchor: 0,
      id: '121',
      index: 4,
    },
    {
      source: '12',
      sourceAnchor: 2,
      target: '1211',
      targetAnchor: 0,
      id: '1212',
      index: 4,
    },
    // 确认状态下的连接边
    {
      source: '2',
      sourceAnchor: 2,
      target: '21',
      targetAnchor: 0,
      id: '211',
      index: 4,
    },
    {
      source: '2',
      sourceAnchor: 2,
      target: '22',
      targetAnchor: 0,
      id: '221',
      index: 4,
    },
    // 故障状态下的连接边
    {
      source: '3',
      sourceAnchor: 2,
      target: '31',
      targetAnchor: 0,
      id: '311',
      index: 4,
    },
    {
      source: '3',
      sourceAnchor: 2,
      target: '32',
      targetAnchor: 0,
      id: '321',
      index: 4,
    },
    {
      source: '3',
      sourceAnchor: 2,
      target: '33',
      targetAnchor: 0,
      id: '331',
      index: 4,
    },
    {
      source: '31',
      sourceAnchor: 2,
      target: '3111',
      targetAnchor: 0,
      id: '3311',
      index: 4,
    },
  ],
}
